apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: 2tier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: admin
          - name: MYSQL_DATABASE
            value: mydb
        ports:
          - containerPort: 3306
        command:
          - sh
          - c
          - |
            mysql -u root --password=admin -h mysql.database -e 'show databases;'
