apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: 2tier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: admin
        ports:
          - containerPort: 3306
      initContainers:
      - name: init-mysql
        image: mysql:5.7
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: admin
        command:
          - "/bin/sh"
          - "-c"
          - "mysql -u root --password=admin -e 'create database mydb; use mydb; CREATE TABLE messages (id INT AUTO_INCREMENT PRIMARY KEY, message TEXT);'"
