apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: 2tier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: admin
          - name: MYSQL_DB
            value: mydb
        ports:
          - containerPort: 3306
      initContainers:
      - name: init-mysql
        image: mysql:5.7
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: admin
          - name: MYSQL_DB
            value: mydb
        command: ['sh', '-c', 'mysql -u root --password=$MYSQL_ROOT_PASSWORD $MYSQL_DB -e "CREATE TABLE messages (id INT AUTO_INCREMENT PRIMARY KEY, message TEXT);"']
