apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: 2tier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: admin
          - name: MYSQL_DATABASE
            value: mydb
        ports:
          - containerPort: 3306
        command:
          - "/bin/sh"
          - "-c"
          - >
            |
            /usr/bin/mysqld --initialize-insecure --user=mysql &&
            /usr/bin/mysqld --user=mysql --console &
            sleep 5 &&
            mysql -h mysql-service -u root --password=admin mydb -e "CREATE TABLE messages (
              id INT AUTO_INCREMENT PRIMARY KEY,
              message TEXT
            );" &&
            /usr/bin/mysqladmin shutdown
